apiVersion: addon.open-cluster-management.io/v1beta1
kind: ClusterManagementAddOn
metadata:
  name: mtv-operator
  annotations:
    addon.open-cluster-management.io/lifecycle: "addon-manager"
spec:
  addOnMeta:
    description: MTV Operator
    displayName: MTV Operator
  defaultConfigs:
    - group: addon.open-cluster-management.io
      resource: addontemplates
      name: mtv-operator
  installStrategy:
    type: Placements
    placements:
    - name: openshift-mtv
      namespace: {{ .Values.global.namespace }}
